name: Exécution du script R après push

on:
  push:
    branches:
      - main  # Ce workflow se déclenche sur un push vers la branche 'main'

jobs:
  run_script:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour exécuter le script

    steps:
      - name: Vérifier le code source
        uses: actions/checkout@v3  # Vérifie le code source du dépôt

      - name: Exécuter le script R
        run: |
          Rscript -e "library(here); library(ggplot2); library(yaml); source(here::here('Execution des rapports.R'))"  # Charger les packages et exécuter le script

      - name: Confirmer l'exécution
        run: echo "Le script R a été exécuté avec succès."
