name: Exécution du script R après push

on:
  push:
    branches:
      - main  # Ce workflow se déclenche sur un push vers la branche 'main'

jobs:
  run_script:
    runs-on: ubuntu-latest  # Utiliser un environnement Ubuntu pour exécuter le script

    steps:
      - name: Vérifier le code source
        uses: actions/checkout@v3  # Vérifie le code source du dépôt

      - name: Installer R et les dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base  # Installe R dans l'environnement

      - name: Installer les packages R nécessaires
        run: |
          R -e "install.packages('here', repos = 'https://cloud.r-project.org')"  # Installer le package 'here'

      - name: Exécuter le script R
        run: |
          Rscript -e "library(here); source(here::here('Execution des rapports.R'))"  # Exécuter le script avec 'here'
          
      - name: Confirmer l'exécution
        run: echo "Le script R a été exécuté avec succès."
