name: Render Multiple R Markdown Reports in 'rapport' folder

on:
  push:
    branches:
      - main

jobs:
  render_reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("here", repos="https://cloud.r-project.org")'
          Rscript -e 'install.packages("rmarkdown", repos="https://cloud.r-project.org")'
          Rscript -e 'install.packages("yaml", repos="https://cloud.r-project.org")'

      - name: Render first RMarkdown report
        run: |
          Rscript -e "library(here); rmarkdown::render(here('scripts', 'Rapport.Rmd'), output_dir = here('rapport'))"

      - name: Render second RMarkdown report
        run: |
          Rscript -e "library(here); rmarkdown::render(here('main.Rmd'), output_dir = here('rapport'))"

      - name: Render second RMarkdown report using yaml
        run: |
          Rscript -e "library(yaml); rmarkdown::render(here('main.Rmd'), output_dir = here('rapport'))"
