name: Render Multiple R Markdown Reports in 'rapport' folder

on:
  push:
    branches:
      - main

jobs:
  render_reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Installer renv et restaurer l'environnement depuis renv.lock
      - name: Restore renv environment
        run: |
          Rscript -e "install.packages('renv', repos='https://cloud.r-project.org')"
          Rscript -e "renv::restore()"

      # Optionnel : installer ici et rmarkdown (si non gérés par renv)
      - name: Install additional dependencies
        run: |
          Rscript -e 'install.packages("here", repos="https://cloud.r-project.org")'
          Rscript -e 'install.packages("rmarkdown", repos="https://cloud.r-project.org")'
          
          

      - name: Render first RMarkdown report
        run: |
          Rscript -e "library(here); rmarkdown::render(here('scripts', 'Rapport.Rmd'), output_dir = here('rapport'))"

      - name: Render second RMarkdown report
        run: |
          Rscript -e "library(here); rmarkdown::render(here('main.Rmd'), output_dir = here('rapport'))"
