name: Render Multiple R Markdown Reports in 'rapport' folder

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  render_reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        run: |
          Rscript -e "install.packages('renv', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages(c('here', 'rmarkdown', 'yaml', 'ggplot2'), repos='https://cloud.r-project.org')"

      - name: Restore renv environment
        run: |
          Rscript -e "renv::restore()"

      - name: Render first RMarkdown report
        run: |
          Rscript -e "library(here); library(rmarkdown); rmarkdown::render(here('scripts', 'Rapport.Rmd'), output_dir = here('rapport'))"

      - name: Render second RMarkdown report
        run: |
          Rscript -e "library(here); library(rmarkdown); rmarkdown::render(here('main.Rmd'), output_dir = here('rapport'))"
