name: Render Multiple R Markdown Reports in 'rapport' folder

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  render_reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Restaurer l'environnement renv
      - name: Restore renv environment
        run: |
          Rscript -e "renv::restore()"
          Rscript -e "renv::status()"

      # Charger les bibliothèques nécessaires
      - name: Load required libraries
        run: |
          Rscript -e "library(renv)"
          Rscript -e "library(here)"
          Rscript -e "library(rmarkdown)"
          Rscript -e "library(ggplot2)"
          Rscript -e "library(yaml)"

      # Rendre le premier rapport RMarkdown
      - name: Render first RMarkdown report
        run: |
          Rscript -e "library(here); library(rmarkdown); rmarkdown::render(here('scripts', 'Rapport.Rmd'), output_dir = here('rapport'))"

      # Rendre le deuxième rapport RMarkdown
      - name: Render second RMarkdown report
        run: |
          Rscript -e "library(here); library(rmarkdown); rmarkdown::render(here('main.Rmd'), output_dir = here('rapport'))"
