name: Render Multiple R Markdown Reports in 'rapport' folder

on:
  push:
    branches:
      - main

jobs:
  render_reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: |
          install.packages("here")
          install.packages("rmarkdown")

      - name: Render first RMarkdown report
        run: |
          Rscript -e "library(here); rmarkdown::render(here("scripts", "Rapport.Rmd"), output_dir = here("rapport"))"

      - name: Render second RMarkdown report
        run: |
          Rscript -e "library(here); rmarkdown::render(here("main.Rmd"), output_dir = here("rapport"))"
