name: Render Multiple R Markdown Reports in 'rapport' folder

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  render_reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Installer 'yaml' d'abord
      - name: Install yaml
        run: Rscript -e "install.packages('yaml', repos='https://cloud.r-project.org')"

      # Restaurer l'environnement renv
      - name: Restore renv environment
        run: |
          Rscript -e "install.packages('renv', repos='https://cloud.r-project.org')"
          Rscript -e "renv::restore()"

      # Installation des autres dépendances
      - name: Install here
        run: Rscript -e "install.packages('here', repos='https://cloud.r-project.org')"

      - name: Install rmarkdown
        run: Rscript -e "install.packages('rmarkdown', repos='https://cloud.r-project.org')"

      - name: Install ggplot2
        run: Rscript -e "install.packages('ggplot2', repos='https://cloud.r-project.org')"

      # Render le premier rapport RMarkdown
      - name: Render first RMarkdown report
        run: |
          Rscript -e "library(here); library(rmarkdown); rmarkdown::render(here('scripts', 'Rapport.Rmd'), output_dir = here('rapport'))"

      # Render le deuxième rapport RMarkdown
      - name: Render second RMarkdown report
        run: |
          Rscript -e "library(here); library(rmarkdown); rmarkdown::render(here('main.Rmd'), output_dir = here('rapport'))"
