name: Export HTML Report After Push

on:
  push:
    branches:
      - main  # Remplace par la branche que tu souhaites surveiller

jobs:
  generate-html:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Vérifier le dépôt
      - name: Check out repository
        uses: actions/checkout@v3

      # Étape 2: Installer R
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      # Étape 3: Installer renv et restaurer les dépendances
      - name: Install renv and restore dependencies
        run: |
          Rscript -e "install.packages('renv', repos = 'https://cloud.r-project.org')"
          Rscript -e "renv::restore()"  # Si tu utilises renv et que tu as un fichier renv.lock

      # Étape 4: Installer les packages nécessaires manuellement
      - name: Install additional R packages
        run: |
          Rscript -e "install.packages(c('rmarkdown', 'yaml', 'ggplot2', 'here', 'dplyr', 'grid', 'gridExtra'), repos = 'https://cloud.r-project.org')"

      # Étape 5: Exécuter le script R pour générer le rapport
      - name: Run R script to generate report
        run: |
          Rscript scripts/Execution_des_rapports.R  # Assure-toi que le chemin est correct

      # Étape 6: Déplacer le fichier HTML généré dans le dossier 'rapport'
      - name: Move HTML to rapport folder
        run: |
          mkdir -p rapport
          mv rapport.html rapport/  # Déplacer le fichier HTML dans le dossier 'rapport'

      # Étape 7: Télécharger le fichier HTML généré en tant qu'artefact
      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: rapport.html
          path: rapport/rapport.html

      # Étape 8: Commit et push les résultats (si applicable)
      - name: Commit results
        run: |
          git config --local user.email "ouedraogocyriaque1@gmail.com"
          git config --local user.name "ChristianCyriaque"
          git add rapport/rapport.html
          git commit -m 'Rapport HTML généré et mis à jour' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
